# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Analyze with Sonarqube
      run:  mvn clean verify sonar:sonar   -Dsonar.projectKey=junit   -Dsonar.host.url=http://10.24.42.90:9000   -Dsonar.login=sqp_24947278cbf1bf9b04ce3e5be819218288345002
      env:
          GITHUB_TOKEN: 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  # Needed to get PR information, if any
          SONAR_PROJECTKEY: junit
          SONAR_TOKEN: sqp_24947278cbf1bf9b04ce3e5be819218288345002
